---
title: "TidyTuesday_01.26.21"
author: "Ochiwar"
date: "11/13/2020"
output:
  pdf_document: 
    latex_engine: xelatex
header-includes:
  - \usepackage{pdflscape}
  - \newcommand{\blandscape}{\begin{landscape}}
  - \newcommand{\elandscape}{\end{landscape}}
  - \usepackage{fancyhdr}
papersize: a4
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      message = FALSE,
                      include = FALSE, 
                      warning = FALSE)
```


```{r load_libraries}

library(tidytuesdayR)
library(ggplot2)
library(tidyverse)
library(waffle)
library(sf)
library(rnaturalearth)
library(patchwork)
library(scales)
library(ggthemes)
library(viridis)
library(ggtext)
library(extrafont)
library(hrbrthemes)
library(lubridate)
library(forcats)
library(showtext)
library(glue)
library(scales)
library(tidytext)
library(countrycode)

library(silgelib)

extrafont::loadfonts(quiet = TRUE)

theme_set(theme_plex())

font_add_google("IBM Plex Sans", "IBMPlexSans")

showtext_auto()

```


# Activity Description


## Load Data 

```{r include=TRUE}

tuesdata <- tidytuesdayR::tt_load(2021, week = 5)

plastics <- tuesdata$plastics


glimpse(plastics)

```

```{r include = TRUE}

plastics %>% 
    filter(year == 2019, 
           parent_company == "Grand Total", 
           country != "EMPTY") %>%  
    select(country, year, hdpe, ldpe,pet, pp, pvc) %>% 
    group_by(country) %>% 
    mutate(total = sum(hdpe, ldpe, pet, pp, pvc, na.rm = T)) %>% 
    arrange(desc(total)) %>% 
    ungroup() %>% 
    top_n(6) %>% 
    pivot_longer(cols = c(hdpe, ldpe, pet, pp, pvc, total), 
                 names_to = "polymer", values_to = "count") %>% 
    mutate (country = as.factor(country), 
            country = str_to_title(country), 
            polymer = str_to_upper(polymer)) %>% 
  select(-year) -> p_clean

```


```{r include = TRUE}

p_clean %>% 
  filter ( !is.na(count)) %>% 
  ggplot(aes(count, reorder_within(country,by = count, within = polymer, fun = max), fill = polymer)) +
  geom_col(show.legend = F) + 
  facet_wrap(~polymer, scales = "free") +
  scale_y_reordered() +
  
  labs(y     = "", 
       x     = "", 
       title = "Top 6 Countries by Total Polymer Waste", 
       subtitle = "A distribution amongst different polymer types is presented")
  




```


```{r}


p2 %>% 
  ggplot(aes(y = reorder_within(country, polymer, count), x = count, fill = polymer)) +
    geom_col(show.legend = FALSE) + 
    facet_wrap(~polymer, scales = "free_x")  +
    theme(
        text = element_text(family = "IBMPlexSans")
    )
 

```


```{r}

top10_2020 <- plastics %>% 
  filter(year == 2020) %>% 
  group_by(country) %>% 
   mutate(
           total = sum(hdpe , ldpe , pet , pp , pvc, na.rm = T)) %>% 
  ungroup() %>% 
  
  group_by(country) %>% 
  summarise(total = mean(total)) %>% 
  arrange(desc(total)) %>% 
  slice(1:10)
 
top10_2020 %>% 
  ggplot(aes(total, fct_reorder(country, total))) +
  geom_col(show.legend = F)  
  

```

Producers of Plastic Waste

```{r}

top_10_plastic_producers <- plastics %>% 
  filter (!parent_company %in%  c("Unbranded","null", "Grand Total") ) %>% 
  group_by(parent_company) %>% 
  count() %>% 
  arrange(desc(n)) %>% 
  filter(n >= 35) %>% 
  pull(parent_company)
  

plastics %>% 
  filter(parent_company %in% top_10_plastic_producers ) %>% 
  select(parent_company, hdpe:pvc, -o)  %>% 
  group_by(parent_company) %>% 
  summarise(total_plastic = sum(hdpe,ldpe,pet,pp,ps,pvc, na.rm = T)) %>% 
  arrange(desc(total_plastic)) %>% 
  
  ggplot(aes(total_plastic, fct_reorder(parent_company, total_plastic))) +
  geom_col() + 
  
  labs(title = "World's Major Plastic Producers", 
       x = "total Plastic Production", 
       y = "")


```


